### ISSUE TITLE
Make conf-autoconf a dev dependency

### ISSUE THREAD

**Issue by palmskog** [validsdp/validsdp#12]
The current released version of validsdp, `coq-validsdp.0.7`, has `conf-autoconf` as a build dependency:
```
"conf-autoconf" {build}
```
However, it can be an inconvenience to users of the `released` opam repo to have to install autoconf (a system package), just to install a Coq package. The current best practice is therefore to declare `conf-autoconf` a development build dependency:
```
"conf-autoconf" {dev & build}
```
This is because `released` packages are expected to be based on tarballs *generated* by autoconf, which removes the need for autoconf itself. See Flocq for examples of this, e.g., the package `coq-flocq.3.4.3`.

**Comment by proux01** [comment]
@palmskog thanks, did that for the OPAM files in this repo and https://github.com/coq/opam-coq-archive/pull/2077 completely removes the `conf-autoconf` dependencies as the `configure.ac` source files of autoconf are not even shipped in the tarballs.
