### ISSUE TITLE
Error in coq-bench for validsdp.1.0.0

### ISSUE THREAD

**Issue by clarus** [validsdp/validsdp#13]
Hello,

There is this error in the coq-bench https://coq-bench.github.io/clean/Linux-x86_64-4.09.1-2.0.6/released/8.12.2/validsdp/1.0.0.html for version 1.0.0 of the package. Do you have an idea of what it is? Is this due to the missing `sdpa` library?

Thanks,
Guillaume Claret

**Comment by proux01** [comment]
Thanks for pointing this. The error seems to come from an old archive that contained a corrupted configure script.
This should be fixed now: https://github.com/coq/opam-coq-archive/pull/2101 but it seems the old corrupted archive is still used, I don't know why.

**Comment by clarus** [comment]
OK, this is due to the delay in the coq-bench for reporting errors then. Thanks. Closing the issue then.
