### ISSUE TITLE
Error "caml_osdp: compiled without CSDP support"

### ISSUE THREAD

**Issue by erikmd** [validsdp/validsdp#2]
- Bug: the osdp-based plugin fails when only the SDPA backend is installed
- Spotted in this Travis CI job: https://travis-ci.com/validsdp/validsdp/jobs/137938888#L3094-L3098

**Comment by proux01** [comment]
Default changed to SDPA.

We should actually fix OSDP so that it chooses as default an installed solver at compile time.

**Comment by erikmd** [comment]
@proux01 Thanks!
You can close this issue if you want (or wait for OSDP to be updated as well to do so)
