### ISSUE TITLE
Prepare stable tarballs and release validsdp 0.6.0

### ISSUE THREAD

**Issue by erikmd** [validsdp/validsdp#8]
- [x] Restore the `make dist` target for ValidSDP
- [x] Restore the `make dist` target for libValidSDP
- [x] Extend the `README.md` files
- [x] Update the wiki: https://github.com/validsdp/validsdp/wiki/How-to-Release 
- [x] Document the tactic `posdef_check` in the main `README.md` (in which branch?)
- [x] Check that the README examples still work (w.r.t. `Require Export`…)
- [x] If need be, move `matrices.v` to the folder `examples` (attic!) or `test-suite` (still tested) and update the _CoqProject.in etc.

**Comment by erikmd** [comment]
@proux01 `make dist` is now OK for ValidSDP; I'll address the rest tomorrow

**Comment by erikmd** [comment]
and I'll need to remove `coq-libvalidsdp.opam` here:

https://github.com/validsdp/validsdp/commit/6ef548baf96a7262db25592b543784c3870eb721#diff-7e056ddc530791272d363e50c1f25647R61

**Comment by erikmd** [comment]
Dear @proux01, I've done all tasks I had proposed yesterday and I propose that your continue that task (I've added in the checklist the items you suggested) and do the release on opam following the suggested procedure (cf. [wiki](https://github.com/validsdp/validsdp/wiki/How-to-Release))

**Comment by proux01** [comment]
PR opened here : https://github.com/coq/opam-coq-archive/pull/1025
